
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      topic: test
      group-id: group1
      message-type:
      auto-offset-reset: earliest
#      security:
#        protocol: SASL_SSL
#      sasl-jaas-config: org.apache.kafka.common.security.scram.ScramLoginModule required username="" password="";
      enable-auto-commit: false
      isolation-level: read_committed

springdoc:
  swagger-ui:
    path: /kafka-message.html

logging:
  level:
    ROOT: INFO
#    org.springframework:
#      transaction: TRACE
#      kafka:
#        transaction: trace
#        core: trace